variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

.pip-cache: &pip-cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ".cache/pip"

.py-rules: &py-rules
  rules:
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"
        - ".flake8"
        - "pyproject.toml"

image: python:3.10

stages:
  - check

py-format:
  stage: check
  before_script:
    - pip install 'black<2024'
  script:
    - black . --check --diff
  needs: []
  <<: *pip-cache
  <<: *py-rules

flake8:
  stage: check
  before_script:
    - pip install 'flake8==6' flake8-awesome
  script:
    - flake8
  needs: []
  <<: *pip-cache
  <<: *py-rules

pytype:
  stage: check
  before_script:
    - pip install pytype
  script:
    - pytype . -d import-error -k -j auto
  needs: []
  <<: *pip-cache
  <<: *py-rules

flynt:
  stage: check
  before_script:
    - pip install flynt
  script:
    - flynt . --line-length 10000 --aggressive --fail-on-change --dry-run
  needs: []
  <<: *pip-cache
  <<: *py-rules

ruff:
  stage: check
  before_script:
    - pip install ruff
  script:
    - ruff check .
  variables:
    PYTHON_VERSION: '3.10'
  needs: []
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ".cache/pip"
      - ".ruff_cache"
  <<: *py-rules
